### ISSUE TITLE
Meeting links all redirect to `https://meet.google.com/migration`

### ISSUE THREAD

**Issue by skray** [ellenli/up-next#46]
I assume this is somehow related to my organization's settings, but starting yesterday every time I try to open a meeting from the Up Next dropdown, the Chrome tab gets redirected to `https://meet.google.com/migration` and I see this message:

![image](https://user-images.githubusercontent.com/3921751/85871597-a2a93200-b79c-11ea-803c-4c01f72e188e.png)

**Comment by ellenli** [comment]
Thanks for flagging this!

**Comment by MrBeardedGuy** [comment]
Hey Ellen, any update on this bug? Keep up the awesome work!

**Comment by lastguest** [comment]
Up +1

**Comment by ellenli** [comment]
[Fixed in version 1.0!](https://apps.apple.com/us/app/up-next/id1355117041?ls=1&mt=12)

**Comment by skray** [comment]
Awesome, thank you!

**Comment by Adamrenak** [comment]
Hi @ellenli  - thanks for resolving this! However - not sure if it's true for everyone, but now when I click a meeting link it just launches my Google Calendar instead of the actual meeting. 

Previously I was working around the Hangouts issue with a chrome plugin to redirect from Hangouts -> Google Meet
